version: "3.8"
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    depends_on:
      - backend
      - frontend
  mongodb:
    image: mongo:5.0.1
    container_name: mongodb
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --port=8888 --host=0.0.0.0
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./frontend:/app:cached"
      - "./frontend/node_modules:/app/node_modules:cached"
    environment:
      - NODE_ENV=development

volumes:
  mongo_data:
